// generated-components/lit/Button.js
import { LitElement, html, css } from "lit";
import { customElement, property, state, query } from "lit/decorators.js";

@customElement("my-button")
export default class Button extends LitElement {
  createRenderRoot() {
    return this;
  }

  @property() disabled: any;
  @property() onClick: any;
  @property() loading: any;
  @property() children: any;
  @property() text: any;

  @state() isPressed = false;

  handleMouseDown() {
    this.isPressed = true;
  }
  handleMouseUp() {
    this.isPressed = false;
  }

  render() {
    return html`

          <button  .style=${getButtonStyle()}  @click=${(event) =>
      (this.disabled ? undefined : this.onClick)()}  @mousedown=${(event) =>
      this.handleMouseDown()}  @mouseup=${(event) =>
      this.handleMouseUp()}  .disabled=${this.disabled} >${
      this.loading
        ? html`<span >Loading...</span>`
        : html`${this.children || this.text}`
    }</button>
        `;
  }
}

// generated-components/vue/Button.vue
<template>
  <button
    :style="getButtonStyle()"
    @click="async (event) => (disabled ? undefined : onClick)()"
    @mousedown="async (event) => handleMouseDown()"
    @mouseup="async (event) => handleMouseUp()"
    :disabled="disabled"
  >
    <template v-if="loading">
      <span>Loading...</span>
    </template>

    <template v-else>
      <slot name="default || text" />
    </template>
  </button>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "button",

  props: ["disabled", "onClick", "loading", "text"],

  data() {
    return { isPressed: false };
  },

  methods: {
    handleMouseDown() {
      this.isPressed = true;
    },
    handleMouseUp() {
      this.isPressed = false;
    },
  },
});
</script>
