// mitosis/react/universal/components/Foo.tsx
"use client";
import * as React from "react";
import { useState } from "react";
import tw from "twrnc";

export interface FooProps {
  foo: number;
  className?: string;
  onClick?: () => void;
}

function Foo(props: FooProps) {
  const [count, setCount] = useState(() => props.foo || 0);

  function increment() {
    count++;
  }

  return (
    <div
      onClick={(event) => {
        increment();
        props.onClick?.();
      }}
      style={{
        padding: "16px",
        border: "1px solid #ccc",
        borderRadius: "8px",
        cursor: "pointer",
        backgroundColor: "#f9f9f9",
      }}
      className={props.className}
    >
      <h3>Universal Foo Component</h3>
      <p>Initial value: {props.foo}</p>
      <p>Current count: {count}</p>
      <button onClick={(event) => increment()}>Increment</button>
    </div>
  );
}

export default Foo;

// generated-components/vue/Foo.vue
<template>
  <div
    @click="
      async (event) => {
        increment();
        onClick?.();
      }
    "
    :style="{
      padding: '16px',
      border: '1px solid #ccc',
      borderRadius: '8px',
      cursor: 'pointer',
      backgroundColor: '#f9f9f9',
    }"
    :class="className"
  >
    <h3>Universal Foo Component</h3>
    <p>Initial value: {{ foo }}</p>
    <p>Current count: {{ count }}</p>
    <button @click="async (event) => increment()">Increment</button>
  </div>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "foo",

  props: ["foo", "onClick", "className"],

  data() {
    return { count: this.foo || 0 };
  },

  methods: {
    increment() {
      this.count++;
    },
  },
});
</script>
