// generated-components/qwik/Card.tsx
import { $, Fragment, Slot, component$, h, useStore } from "@builder.io/qwik";

export const handleMouseEnter = function handleMouseEnter(props, state) {
  if (props.hoverable) {
    state.isHovered = true;
  }
};
export const handleMouseLeave = function handleMouseLeave(props, state) {
  if (props.hoverable) {
    state.isHovered = false;
  }
};
export const Card = component$((props: any) => {
  const state = useStore<any>({ isHovered: false });

  return (
    <div
      style={cardStyle}
      onMouseEnter$={$((event) => handleMouseEnter(props, state))}
      onMouseLeave$={$((event) => handleMouseLeave(props, state))}
      onClick$={$((event) => props.onClick())}
      class={props.className}
    >
      {props.image ? (
        <img
          src={props.image}
          alt={props.title || "Card image"}
          style={imageStyle}
        />
      ) : null}
      {props.title ? <h3 style={titleStyle}>{props.title}</h3> : null}
      {props.subtitle ? <p style={subtitleStyle}>{props.subtitle}</p> : null}
      {props.children ? (
        <div>
          <Slot></Slot>
        </div>
      ) : null}
    </div>
  );
});

export default Card;

// generated-components/stencil/Card.js
import {
  Component,
  h,
  Fragment,
  Event,
  EventEmitter,
  Prop,
  State,
} from "@stencil/core";

@Component({
  tag: "card",
})
export class Card {
  @Prop() hoverable: any;
  @Event() click: any;
  @Prop() className: any;
  @Prop() image: any;
  @Prop() title: any;
  @Prop() subtitle: any;
  @State() isHovered = false;

  handleMouseEnter() {
    if (this.hoverable) {
      this.isHovered = true;
    }
  }
  handleMouseLeave() {
    if (this.hoverable) {
      this.isHovered = false;
    }
  }

  componentDidLoad() {}

  render() {
    return (
      <div
        class={this.className}
        style={cardStyle}
        onMouseEnter={() => this.handleMouseEnter()}
        onMouseLeave={() => this.handleMouseLeave()}
        onClick={() => this.click.emit()}
      >
        {this.image ? (
          <img
            src={this.image}
            alt={this.title || "Card image"}
            style={imageStyle}
          />
        ) : null}
        {this.title ? <h3 style={titleStyle}>{this.title}</h3> : null}
        {this.subtitle ? <p style={subtitleStyle}>{this.subtitle}</p> : null}
        {this.children ? (
          <div>
            <slot></slot>
          </div>
        ) : null}
      </div>
    );
  }
}
