// generated-components/stencil/Button.js
import {
  Component,
  h,
  Fragment,
  Event,
  EventEmitter,
  Prop,
  State,
} from "@stencil/core";

@Component({
  tag: "button",
})
export class Button {
  @Prop() disabled: any;
  @Event() click: any;
  @Prop() loading: any;
  @Prop() text: any;
  @State() isPressed = false;

  handleMouseDown() {
    this.isPressed = true;
  }
  handleMouseUp() {
    this.isPressed = false;
  }

  componentDidLoad() {}

  render() {
    return (
      <button
        style={getButtonStyle()}
        onClick={() => (this.disabled ? undefined : this.click)()}
        onMouseDown={() => this.handleMouseDown()}
        onMouseUp={() => this.handleMouseUp()}
        disabled={this.disabled}
      >
        {this.loading ? <span>Loading...</span> : this.children || this.text}
      </button>
    );
  }
}

// generated-components/qwik/Button.tsx
import { $, Fragment, component$, h, useStore } from "@builder.io/qwik";

export const handleMouseDown = function handleMouseDown(props, state) {
  state.isPressed = true;
};
export const handleMouseUp = function handleMouseUp(props, state) {
  state.isPressed = false;
};
export const Button = component$((props: any) => {
  const state = useStore<any>({ isPressed: false });

  return (
    <button
      style={getButtonStyle()}
      onClick$={$((event) => (props.disabled ? undefined : props.onClick)())}
      onMouseDown$={$((event) => handleMouseDown(props, state))}
      onMouseUp$={$((event) => handleMouseUp(props, state))}
      disabled={props.disabled}
    >
      {props.loading ? (
        <span>Loading...</span>
      ) : (
        <>{props.children || props.text}</>
      )}
    </button>
  );
});

export default Button;
