// mitosis/react/universal/components/Card.tsx
"use client";
import * as React from "react";
import { useState } from "react";
import tw from "twrnc";

export interface CardProps {
  title?: string;
  subtitle?: string;
  image?: string;
  children?: any;
  hoverable?: boolean;
  className?: string;
  onClick?: () => void;
}

function Card(props: CardProps) {
  const [isHovered, setIsHovered] = useState(() => false);

  function handleMouseEnter() {
    if (props.hoverable) {
      setIsHovered(true);
    }
  }

  function handleMouseLeave() {
    if (props.hoverable) {
      setIsHovered(false);
    }
  }

  return (
    <div
      style={cardStyle}
      onMouseEnter={(event) => handleMouseEnter()}
      onMouseLeave={(event) => handleMouseLeave()}
      onClick={(event) => props.onClick()}
      className={props.className}
    >
      {props.image ? (
        <img
          src={props.image}
          alt={props.title || "Card image"}
          style={imageStyle}
        />
      ) : null}
      {props.title ? <h3 style={titleStyle}>{props.title}</h3> : null}
      {props.subtitle ? <p style={subtitleStyle}>{props.subtitle}</p> : null}
      {props.children ? <div>{props.children}</div> : null}
    </div>
  );
}

export default Card;

// generated-components/solid/Card.tsx
import { Show, createSignal, createMemo } from "solid-js";

function Card(props: any) {
  const [isHovered, setIsHovered] = createSignal(false);

  function handleMouseEnter() {
    if (props.hoverable) {
      setIsHovered(true);
    }
  }

  function handleMouseLeave() {
    if (props.hoverable) {
      setIsHovered(false);
    }
  }

  return (
    <>
      <div
        class={props.className}
        style={cardStyle}
        onMouseEnter={(event) => handleMouseEnter()}
        onMouseLeave={(event) => handleMouseLeave()}
        onClick={(event) => props.onClick()}
      >
        <Show when={props.image}>
          <img
            src={props.image}
            alt={props.title || "Card image"}
            style={imageStyle}
          />
        </Show>
        <Show when={props.title}>
          <h3 style={titleStyle}>{props.title}</h3>
        </Show>
        <Show when={props.subtitle}>
          <p style={subtitleStyle}>{props.subtitle}</p>
        </Show>
        <Show when={props.children}>
          <div>{props.children}</div>
        </Show>
      </div>
    </>
  );
}

export default Card;
