// generated-components/vue/Card.vue
<template>
  <div
    :style="cardStyle"
    @mouseenter="async (event) => handleMouseEnter()"
    @mouseleave="async (event) => handleMouseLeave()"
    @click="async (event) => onClick()"
    :class="className"
  >
    <template v-if="image">
      <img :src="image" :alt="title || 'Card image'" :style="imageStyle" />
    </template>

    <template v-if="title">
      <h3 :style="titleStyle">{{ title }}</h3>
    </template>

    <template v-if="subtitle">
      <p :style="subtitleStyle">{{ subtitle }}</p>
    </template>

    <template v-if="$slots.default">
      <div><slot /></div>
    </template>
  </div>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "card",

  props: ["hoverable", "onClick", "className", "image", "title", "subtitle"],

  data() {
    return { isHovered: false };
  },

  methods: {
    handleMouseEnter() {
      if (this.hoverable) {
        this.isHovered = true;
      }
    },
    handleMouseLeave() {
      if (this.hoverable) {
        this.isHovered = false;
      }
    },
  },
});
</script>

// generated-components/svelte/Card.svelte
<script lang="ts">
  export let hoverable;
  export let onClick;
  export let className;
  export let image;
  export let title;
  export let subtitle;

  function stringifyStyles(stylesObj) {
    let styles = "";
    for (let key in stylesObj) {
      const dashedKey = key.replace(/[A-Z]/g, function (match) {
        return "-" + match.toLowerCase();
      });
      styles += dashedKey + ":" + stylesObj[key] + ";";
    }
    return styles;
  }

  function handleMouseEnter() {
    if (hoverable) {
      isHovered = true;
    }
  }
  function handleMouseLeave() {
    if (hoverable) {
      isHovered = false;
    }
  }

  let isHovered = false;
</script>

<div
  style={stringifyStyles(cardStyle)}
  on:mouseenter={(event) => {
    handleMouseEnter();
  }}
  on:mouseleave={(event) => {
    handleMouseLeave();
  }}
  on:click={(event) => {
    onClick();
  }}
  class={className}
>
  {#if image}
    <img
      style={stringifyStyles(imageStyle)}
      src={image}
      alt={title || "Card image"}
    />
  {/if}
  {#if title}
    <h3 style={stringifyStyles(titleStyle)}>{title}</h3>
  {/if}
  {#if subtitle}
    <p style={stringifyStyles(subtitleStyle)}>{subtitle}</p>
  {/if}
  {#if $$slots.default}
    <div><slot /></div>
  {/if}
</div>
